spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_theater?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-while-idle: true
    validation-query: SELECT 1
  redis:
    host: 127.0.0.1
    #redis密码，没有密码的可以用～表示
    password: dw@@2020
    port: 6379

  mvc:
    static-path-pattern: /static/**

  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/public/

  session:
    redis:
     store-type: redis
     flush-mode: on_save
     namespace: spring:session

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
    check-template: true
    servlet:
      content-type: text/html
    encoding: utf-8

server:
  servlet:
    session:
      timeout: 3600
    context-path: /
  port: 8888

mybatis:
  type-aliases-package: com.ws.mapper
  mapper-locations: classpath*:mapper/*.xml
  configLocation: classpath:mybatis-config.xml

logging:
  level:
    com.ws:
        mapper: debug

#OSS
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyid: LTAI4FusZe3wH1ChUWpwVYKB
    keysecret: 6qr4uA8oFjGDT2gFePWFOBraUCypa3
    bucketname: java4all-file
    filehost: img


